package catalog

// parity_test.go — the cross-language acceptance test: the Go applier, run on
// the VENDORED catalog recipe, must reproduce mio-page-catalog's golden
// fixtures (generated by the TS reference applier, normalized modulo ids) for
// every template, every variant, and every page template. This is the Go port
// of mio-page-catalog@f75ddf4 tests/hub-parity.test.ts.
//
// Two independent parity proofs guard the port:
//   - the whole-catalog digest (Digest == meta.digest == the pinned constant)
//     proves CanonicalJSON matches the TS canonicalizer byte-for-byte over 66 KB
//     of real data;
//   - the golden fixtures prove InstantiateTemplate reproduces the reference
//     applier per recipe.

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// pinnedDigest is the catalog digest at the vendored revision (the commit in
// CATALOG_REF). It is an INDEPENDENT third value: TestDigest_MatchesMetaAndPin
// cross-checks the Go canonicalizer's computed digest, the meta.digest carried
// inside catalog.json, and this constant, so a re-vendor that swapped the body
// without refreshing the fixtures cannot pass unnoticed.
//
// scripts/update_catalog_pin.sh rewrites exactly this line — it is the only Go
// source a re-pin touches, which is why it is anchored on its own line and kept
// free of any other pin metadata.
const pinnedDigest = "sha256:32a5cf74c7a13a4899ad255cd84a2577110fb78dce801cbe53cc3234348d0a15"

func fixtureName(id, variant string) string {
	if variant != "" {
		return id + "." + variant + ".json"
	}
	return id + ".json"
}

// TestDigest_MatchesMetaAndPin proves the Go canonicalizer + sha256 agree with
// the TS reference over the entire catalog (the strongest byte-parity signal).
func TestDigest_MatchesMetaAndPin(t *testing.T) {
	c := loadForTest(t)
	computed, err := Digest(c.Raw())
	if err != nil {
		t.Fatalf("Digest: %v", err)
	}
	if computed != pinnedDigest {
		t.Errorf("computed digest %s != pinned %s (CanonicalJSON diverges from the TS canonicalizer)", computed, pinnedDigest)
	}
	if c.DigestPinned() != pinnedDigest {
		t.Errorf("vendored meta.digest %s != pinned %s", c.DigestPinned(), pinnedDigest)
	}
	if computed != c.DigestPinned() {
		t.Errorf("computed digest %s != vendored meta.digest %s", computed, c.DigestPinned())
	}
}

// TestPinnedRef_WellFormed guards the machine-readable half of the pin. The
// staleness workflow compares CATALOG_REF byte-for-byte against the SHA the
// GitHub API reports for mio-page-catalog's HEAD; a short ref, a tag name, or a
// stray "ref: " prefix would make every run look stale forever and open a bump
// PR a day. Cheap assertion, expensive failure mode.
func TestPinnedRef_WellFormed(t *testing.T) {
	ref := PinnedRef()
	if len(ref) != 40 {
		t.Fatalf("CATALOG_REF = %q (len %d); want a full 40-char commit SHA", ref, len(ref))
	}
	for _, r := range ref {
		if !strings.ContainsRune("0123456789abcdef", r) {
			t.Fatalf("CATALOG_REF = %q; want lowercase hex only", ref)
		}
	}
}

// TestGoldenFixtureSet_ExactlyMatches guards against a fixture silently going
// missing or lingering: on-disk set must equal (templates × variants) ∪
// pageTemplates. Port of hub-parity.test.ts's fixture-set guard.
func TestGoldenFixtureSet_ExactlyMatches(t *testing.T) {
	c := loadForTest(t)
	want := map[string]bool{}
	for _, tmpl := range c.Templates {
		want[fixtureName(tmpl.ID, "")] = true
		for v := range tmpl.Variants {
			want[fixtureName(tmpl.ID, v)] = true
		}
	}
	for _, p := range c.PageTemplates {
		want[fixtureName(p.ID, "")] = true
	}

	entries, err := os.ReadDir(filepath.Join("testdata", "fixtures"))
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	got := map[string]bool{}
	for _, e := range entries {
		if filepath.Ext(e.Name()) == ".json" {
			got[e.Name()] = true
		}
	}

	for name := range want {
		if !got[name] {
			t.Errorf("missing golden fixture %q", name)
		}
	}
	for name := range got {
		if !want[name] {
			t.Errorf("stray golden fixture %q (no matching template/variant/page)", name)
		}
	}
}

// TestGoldenParity_Templates: applier(catalog.template, {variant}) normalized ==
// golden fixture, for every section template and every variant.
func TestGoldenParity_Templates(t *testing.T) {
	c := loadForTest(t)
	for _, tmpl := range c.Templates {
		variants := []string{""}
		vs := make([]string, 0, len(tmpl.Variants))
		for v := range tmpl.Variants {
			vs = append(vs, v)
		}
		sort.Strings(vs)
		variants = append(variants, vs...)

		for _, v := range variants {
			name := tmpl.ID
			if v != "" {
				name += " :: " + v
			}
			t.Run(name, func(t *testing.T) {
				assertGoldenParity(t, tmpl, v)
			})
		}
	}
}

// TestGoldenParity_PageTemplates: same criterion for whole-page compositions.
func TestGoldenParity_PageTemplates(t *testing.T) {
	c := loadForTest(t)
	for _, p := range c.PageTemplates {
		t.Run(p.ID, func(t *testing.T) {
			assertGoldenParity(t, p, "")
		})
	}
}

func assertGoldenParity(t *testing.T, tmpl Template, variant string) {
	t.Helper()
	instantiated, err := InstantiateTemplate(tmpl, variant, NewUUIDv7Gen())
	if err != nil {
		t.Fatalf("InstantiateTemplate(%s, %q): %v", tmpl.ID, variant, err)
	}
	got := NormalizeIDs(instantiated)
	golden := readJSONNumber(t, filepath.Join("testdata", "fixtures", fixtureName(tmpl.ID, variant)))

	gotCanon := mustCanonical(t, got)
	goldenCanon := mustCanonical(t, golden)
	if gotCanon != goldenCanon {
		t.Errorf("applier output diverges from golden fixture %s\n got=%s\n want=%s",
			fixtureName(tmpl.ID, variant), gotCanon, goldenCanon)
	}
}
