package client

// resolve.go — name/slug → id resolution for the user-facing flags and args.
//
// The CLI accepts a RAW id everywhere an id is expected; that path is and must
// stay first-class (it skips every list call and never touches the network for
// resolution). On top of that, this file lets a human-friendly NAME or SLUG be
// supplied instead, resolving it to the canonical id with a TARGETED, per-
// resource strategy.
//
// Design rules (a prior Codex review warned against a generic "list the first
// page and match" sweep, so the strategy is resource-aware):
//
//   - id passthrough: a value that is already id-shaped — a UUID (the real
//     production id, generated by the backend UUIDMixin as a uuid7) OR one of
//     the CLI's documented prefix conventions (team_/hub_/tag_/ctt_/tcid…) — is
//     returned unchanged with NO API call.
//   - server filter first: when the backend exposes a server-side filter for the
//     lookup (contacts support `filter[email]`, an exact normalized-email match),
//     use it — one narrow request, no client-side scan.
//   - list + match fallback: resources with no server-side name filter (teams,
//     hubs, tags) are listed with a sane page cap and matched client-side, slug
//     first then name, case-insensitively.
//   - never auto-pick an ambiguous name: 0 matches and >1 match are BOTH errors.
//     The >1 case lists the candidate id+name so the caller can disambiguate by
//     passing a raw id.
//   - per-process cache: a resolved (kind,value)→id pair is memoized so repeat
//     references in a single command (or a single process) don't re-list.

import (
	"context"
	"fmt"
	"net/url"
	"strings"
	"sync"
)

// resolveListCap bounds the list+match fallback for resources with no server
// filter. A team's tag/hub/team counts are small in practice; capping the page
// keeps the lookup a single bounded request instead of an unbounded sweep. If a
// name genuinely lives beyond this cap the user can always pass the raw id.
const resolveListCap = 200

// id-prefix conventions per resource. Production ids are bare UUIDs (uuid7 via
// the backend UUIDMixin), but the docs, examples, tests, and existing scripts
// use friendly prefixes — and BOTH spellings appear in the wild (e.g. a team is
// "team_…" in the README but "t_…" in the contract tests). A value carrying any
// of its resource's prefixes is treated as a first-class id (passthrough, no API
// call). Names/slugs do not look like these tokens, so prefix matching is safe.
var (
	teamIDPrefixes    = []string{"team_", "t_"}
	hubIDPrefixes     = []string{"hub_", "h_"}
	tagIDPrefixes     = []string{"tag_"}
	contactIDPrefixes = []string{"ctt_", "contact_", "tcid_", "tc_"}
)

// resolveCache memoizes (kind,value)→id for the lifetime of the process so a
// command that references the same name twice lists at most once. The CLI runs
// one command per process, so a simple mutex-guarded map is sufficient; there is
// no eviction because the process is short-lived.
type resolveCache struct {
	mu sync.Mutex
	m  map[string]string
}

func (c *resolveCache) get(key string) (string, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.m == nil {
		return "", false
	}
	v, ok := c.m[key]
	return v, ok
}

func (c *resolveCache) put(key, id string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.m == nil {
		c.m = make(map[string]string)
	}
	c.m[key] = id
}

// cacheKey namespaces a cached lookup by kind + the optional parent scope (the
// team id for hub/tag/contact lookups) so a name that means different ids under
// different teams never collides.
func cacheKey(kind, scope, value string) string {
	return kind + "\x00" + scope + "\x00" + value
}

// isUUID reports whether s is a canonical 8-4-4-4-12 hex UUID (the real
// production id shape — the backend mints uuid7 values via UUIDMixin). Matching
// is case-insensitive and tolerant of the standard hyphenation only; a bare
// 32-hex value is intentionally NOT treated as a UUID because it is
// indistinguishable from an opaque name token.
func isUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, r := range s {
		switch i {
		case 8, 13, 18, 23:
			if r != '-' {
				return false
			}
		default:
			if !isHexDigit(r) {
				return false
			}
		}
	}
	return true
}

func isHexDigit(r rune) bool {
	return (r >= '0' && r <= '9') || (r >= 'a' && r <= 'f') || (r >= 'A' && r <= 'F')
}

// hasIDPrefix reports whether value carries one of the given CLI id-prefix
// conventions (e.g. "team_", "hub_"). These prefixes are a CLI/docs convention
// — production ids are UUIDs — but they appear throughout the docs, examples,
// tests, and existing scripts, so a prefixed value must be treated as a
// first-class id (passthrough, no API call).
func hasIDPrefix(value string, prefixes ...string) bool {
	for _, p := range prefixes {
		if strings.HasPrefix(value, p) {
			return true
		}
	}
	return false
}

// isIDShaped reports whether value should be treated as an already-resolved id
// for a resource whose ids may carry any of the given CLI prefixes. A UUID is
// always id-shaped regardless of prefix.
func isIDShaped(value string, prefixes ...string) bool {
	return isUUID(value) || hasIDPrefix(value, prefixes...)
}

// ResolveTeam resolves a team NAME or SLUG to a team id. An id-shaped value
// (UUID or "team_…") is returned unchanged with no API call. Otherwise it lists
// the caller's teams and matches slug-first then name, case-insensitively.
//
// Teams have no server-side name filter, so this is a bounded list + match.
func (c *Client) ResolveTeam(ctx context.Context, value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("empty team identifier")
	}
	if isIDShaped(value, teamIDPrefixes...) {
		return value, nil
	}
	key := cacheKey("team", "", value)
	if id, ok := c.resolveCache.get(key); ok {
		return id, nil
	}

	col, err := c.List(ctx, "/api/teams", listCapQuery())
	if err != nil {
		return "", err
	}
	id, err := matchByNameOrSlug("team", "teams", value, col.Data)
	if err != nil {
		return "", err
	}
	c.resolveCache.put(key, id)
	return id, nil
}

// ResolveHub resolves a hub NAME or SLUG to a hub id within the given team. An
// id-shaped value (UUID or "hub_…") is returned unchanged with no API call.
// Otherwise it lists the team's hubs and matches slug-first then name.
//
// Hubs have no server-side name filter, so this is a bounded list + match.
func (c *Client) ResolveHub(ctx context.Context, teamID, value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("empty hub identifier")
	}
	if isIDShaped(value, hubIDPrefixes...) {
		return value, nil
	}
	if teamID == "" {
		return "", fmt.Errorf("cannot resolve hub %q by name without a team in context", value)
	}
	key := cacheKey("hub", teamID, value)
	if id, ok := c.resolveCache.get(key); ok {
		return id, nil
	}

	col, err := c.List(ctx, fmt.Sprintf("/api/teams/%s/hubs", teamID), listCapQuery())
	if err != nil {
		return "", err
	}
	id, err := matchByNameOrSlug("hub", "hubs", value, col.Data)
	if err != nil {
		return "", err
	}
	c.resolveCache.put(key, id)
	return id, nil
}

// ResolveTag resolves a tag NAME or SLUG to a tag id within the given team. An
// id-shaped value (UUID or "tag_…") is returned unchanged with no API call.
// Otherwise it lists the team's tags and matches slug-first then name.
//
// Tags have no server-side name filter, so this is a bounded list + match.
func (c *Client) ResolveTag(ctx context.Context, teamID, value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("empty tag identifier")
	}
	if isIDShaped(value, tagIDPrefixes...) {
		return value, nil
	}
	if teamID == "" {
		return "", fmt.Errorf("cannot resolve tag %q by name without a team in context", value)
	}
	key := cacheKey("tag", teamID, value)
	if id, ok := c.resolveCache.get(key); ok {
		return id, nil
	}

	col, err := c.List(ctx, fmt.Sprintf("/api/teams/%s/tags", teamID), listCapQuery())
	if err != nil {
		return "", err
	}
	id, err := matchByNameOrSlug("tag", "tags", value, col.Data)
	if err != nil {
		return "", err
	}
	c.resolveCache.put(key, id)
	return id, nil
}

// ResolveContactByEmail resolves a contact EMAIL to a team-contact id within the
// given team. An id-shaped value (UUID or "ctt_…"/"tcid…") is returned unchanged
// with no API call. Otherwise it uses the backend's SERVER-SIDE `filter[email]`
// exact-match filter — a single narrow request, not a client-side scan.
//
// The contacts list endpoint normalizes the email server-side (trim + lower),
// so an exact match returns the single team-contact for that address.
func (c *Client) ResolveContactByEmail(ctx context.Context, teamID, email string) (string, error) {
	email = strings.TrimSpace(email)
	if email == "" {
		return "", fmt.Errorf("empty contact email")
	}
	// A raw contact id may legitimately be passed where an email is expected
	// (the flag accepts either); treat an id-shaped value as already resolved.
	// An address always contains '@', so it can never collide with an id token.
	if !strings.Contains(email, "@") && isIDShaped(email, contactIDPrefixes...) {
		return email, nil
	}
	if teamID == "" {
		return "", fmt.Errorf("cannot resolve contact %q by email without a team in context", email)
	}
	key := cacheKey("contact-email", teamID, strings.ToLower(email))
	if id, ok := c.resolveCache.get(key); ok {
		return id, nil
	}

	q := url.Values{}
	q.Set("filter[email]", email)
	q.Set("page[size]", itoaCap(resolveListCap))
	col, err := c.List(ctx, fmt.Sprintf("/api/teams/%s/contacts", teamID), q)
	if err != nil {
		return "", err
	}
	switch len(col.Data) {
	case 0:
		return "", fmt.Errorf("no contact with email %q — run 'mio contacts list'", email)
	case 1:
		id := col.Data[0].ID
		c.resolveCache.put(key, id)
		return id, nil
	default:
		// An exact-email filter should be unique; if the backend ever returns
		// multiple, surface them rather than silently picking one.
		return "", ambiguousError("contact", email, col.Data)
	}
}

// matchByNameOrSlug finds the single resource in data whose slug (preferred) or
// name matches value case-insensitively. It returns a not-found error on 0
// matches and an ambiguity error (listing candidates) on >1 — it NEVER picks one
// of several. kind is the singular human noun ("tag"); listCmd is the CLI list
// command noun used in the not-found hint ("tags").
func matchByNameOrSlug(kind, listCmd, value string, data []Resource) (string, error) {
	want := strings.ToLower(value)

	// Pass 1: slug (the canonical, unique-per-team identifier).
	var slugHits []Resource
	for _, r := range data {
		if slug, ok := r.Attributes["slug"].(string); ok && strings.ToLower(slug) == want {
			slugHits = append(slugHits, r)
		}
	}
	if len(slugHits) == 1 {
		return slugHits[0].ID, nil
	}
	if len(slugHits) > 1 {
		return "", ambiguousError(kind, value, slugHits)
	}

	// Pass 2: name (may be non-unique).
	var nameHits []Resource
	for _, r := range data {
		if name, ok := r.Attributes["name"].(string); ok && strings.ToLower(name) == want {
			nameHits = append(nameHits, r)
		}
	}
	switch len(nameHits) {
	case 0:
		return "", fmt.Errorf("no %s named %q — run 'mio %s list'", kind, value, listCmd)
	case 1:
		return nameHits[0].ID, nil
	default:
		return "", ambiguousError(kind, value, nameHits)
	}
}

// ambiguousError builds an error that lists every candidate id+name for an
// ambiguous name match so the operator can re-run with a raw id. It never
// resolves the ambiguity itself.
func ambiguousError(kind, value string, candidates []Resource) error {
	var sb strings.Builder
	fmt.Fprintf(&sb, "%s name %q is ambiguous — %d matches; pass a raw id instead:",
		kind, value, len(candidates))
	for _, r := range candidates {
		name, _ := r.Attributes["name"].(string)
		if name == "" {
			name, _ = r.Attributes["slug"].(string)
		}
		fmt.Fprintf(&sb, "\n  %s  %s", r.ID, name)
	}
	return fmt.Errorf("%s", sb.String())
}

// listCapQuery returns a query that caps the page size for a list+match
// resolution so the fallback is a single bounded request.
func listCapQuery() url.Values {
	q := url.Values{}
	q.Set("page[size]", itoaCap(resolveListCap))
	return q
}

// itoaCap renders a small positive cap as a decimal string without pulling in
// strconv (matching the dependency-free itoa helper in the cmd package).
func itoaCap(n int) string {
	if n <= 0 {
		return "1"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}
